### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by VeitIsopp** [SociallyIneptWeeb/AICoverGen#1]
So when running the requirment installation the provided numpy version (1.23.5) is not compatible with fairseq, librosa, onnxruntime-gpu.

ERROR: Cannot install -r requirements.txt (line 14), -r requirements.txt (line 3), -r requirements.txt (line 4), numpy==1.23.5 and onnxruntime-gpu==1.15.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.5
    fairseq 0.12.2 depends on numpy; python_version >= "3.7"
    librosa 0.6.3 depends on numpy>=1.8.0
    onnxruntime-gpu 1.15.1 depends on numpy>=1.24.2
    The user requested numpy==1.23.5
    fairseq 0.12.2 depends on numpy; python_version >= "3.7"
    librosa 0.6.3 depends on numpy>=1.8.0
    onnxruntime-gpu 1.15.0 depends on numpy>=1.24.2

Now if I loosen the package range, I can install everything, but then when running it we are faced with the following issue:

Traceback (most recent call last):
  File "C:\AICoverGen\src\main.py", line 12, in <module>
    from mdx import run_mdx
  File "C:\AICoverGen\src\mdx.py", line 8, in <module>
    import librosa
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\constantq.py", line 1059, in <module>
    dtype=np.complex,
          ^^^^^^^^^^
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
'ab_channel' is not recognized as an internal or external command,
operable program or batch file.

I was just wondering how you resolved this issue? Since it seems that even the given error is a dependency issue related to librosa.

**Comment by reallypyst** [comment]
I seem to be experiencing the same issue. I attempted to modify \Python311\site-packages\librosa\core\constantq.py with both of the error message suggestions (`complex` and `np.complex128`) however this just led to further errors.

**Comment by SociallyIneptWeeb** [comment]
Package                Version
---------------------- -----------
aiohttp                3.8.4
aiosignal              1.3.1
annotated-types        0.5.0
antlr4-python3-runtime 4.8
anyio                  3.7.1
async-timeout          4.0.2
attrs                  23.1.0
audioread              3.0.0
backoff                2.2.1
bitarray               2.7.6
boto3                  1.28.3
botocore               1.31.3
Brotli                 1.0.9
certifi                2023.5.7
cffi                   1.15.1
charset-normalizer     3.2.0
click                  8.1.5
colorama               0.4.6
coloredlogs            15.0.1
Cython                 0.29.36
decorator              5.1.1
deemix                 3.6.6
deezer-py              1.3.7
dnspython              2.4.0
email-validator        2.0.0.post2
exceptiongroup         1.1.2
fairseq                0.12.2
faiss-cpu              1.7.3
fastapi                0.100.0
ffmpeg-python          0.2.0
filelock               3.12.2
flatbuffers            23.5.26
frozenlist             1.4.0
future                 0.18.3
h11                    0.14.0
httpcore               0.17.3
httptools              0.6.0
httpx                  0.24.1
humanfriendly          10.0
hydra-core             1.0.7
idna                   3.4
itsdangerous           2.1.2
Jinja2                 3.1.2
jmespath               1.0.1
joblib                 1.3.1
librosa                0.8.1
llvmlite               0.40.1
lxml                   4.9.3
MarkupSafe             2.1.3
mpmath                 1.3.0
multidict              6.0.4
mutagen                1.46.0
networkx               3.1
numba                  0.57.1
numpy                  1.23.5
omegaconf              2.0.6
onnxruntime-gpu        1.15.1
orjson                 3.9.2
packaging              23.1
pedalboard             0.7.4
Pillow                 10.0.0
pip                    21.1.2
platformdirs           3.9.1
pooch                  1.7.0
portalocker            2.7.0
praat-parselmouth      0.4.3
protobuf               4.23.4
py-cpuinfo             9.0.0
pycparser              2.21
pycryptodomex          3.18.0
pydantic               2.0.3
pydantic-core          2.3.0
pydantic-extra-types   2.0.0
pydantic-settings      2.0.2
pydub                  0.25.1
pyreadline3            3.4.1
python-dateutil        2.8.2
python-dotenv          1.0.0
python-multipart       0.0.6
pywin32                306
pyworld                0.3.3
PyYAML                 6.0
regex                  2023.6.3
requests               2.31.0
resampy                0.4.2
runpod                 0.9.11
s3transfer             0.6.1
sacrebleu              2.3.1
scikit-learn           1.3.0
scipy                  1.11.1
setuptools             57.0.0
six                    1.16.0
sniffio                1.3.0
soundfile              0.12.1
starlette              0.27.0
sympy                  1.12
tabulate               0.9.0
threadpoolctl          3.2.0
torch                  2.0.1+cu118
torchaudio             2.0.2+cu118
torchcrepe             0.0.15
tqdm                   4.65.0
tqdm-loggable          0.1.4
typing-extensions      4.7.1
ujson                  5.8.0
urllib3                1.26.16
uvicorn                0.23.0
watchfiles             0.19.0
websockets             11.0.3
wheel                  0.36.2
yarl                   1.9.2
yt-dlp                 2023.7.6

These are the dependency versions I'm usiing in my venv. You can check if any of your dependency versions are different and pip install that version.

**Comment by reallypyst** [comment]
Okay so after a day of tinkering and troubleshooting, I was able to get it working. Ultimately the issue seems to be related to the version of python used. 
Previously I was using 3.11 and even with dependencies matching the ones you provided exactly, I would always receive that same error. As soon as I switched to 3.9, it worked perfectly. Just to verify, I tested this on my second PC using both versions and was able to replicate it exactly, so there's something about Python 3.11 that isn't playing nice with these packages.

**Comment by SociallyIneptWeeb** [comment]
I see. Thank you for testing it out. I'll include in the readme to use python 3.9 for now.

**Comment by reallypyst** [comment]
Thank you for the awesome work! Love the webui btw

**Comment by SociallyIneptWeeb** [comment]
Np! It was thanks to another pull request that I decided to work on the webui.
