### ISSUE TITLE
run_mdx gpu

### ISSUE THREAD

**Issue by cometothed4rkside** [SociallyIneptWeeb/AICoverGen#10]
Hi run_mdx is using cpu instead of gpu. Do you have any information about this?

**Comment by SociallyIneptWeeb** [comment]
Do you have a Nvidia GPU or an AMD GPU?

**Comment by SociallyIneptWeeb** [comment]
Is it not using your GPU at all? I believe it sometimes switches between both GPU and CPU.

**Comment by SociallyIneptWeeb** [comment]
Ok nice that should be working now.
