### ISSUE TITLE
Generate using CPU

### ISSUE THREAD

**Issue by Hulababa-22** [SociallyIneptWeeb/AICoverGen#112]
my gpu is strong enough to generate within 2 minutes but i am wondering if maybe i can try using my cpu to generate because my cpu is a 14 core 28 thread cpu, its a "xeon e5 2690 v4" i have that cpu cause its cheap lmao not even using it that much... anyway can i generate using CPU?

**Comment by TheMaskedMan00** [comment]
No you cant. https://blog.purestorage.com/purely-informational/cpu-vs-gpu-for-machine-learning/
