### ISSUE TITLE
[BUG] Regenerate Error

### ISSUE THREAD

**Issue by cometothed4rkside** [SociallyIneptWeeb/AICoverGen#12]
WebUi does not regenerate when the pitch value changes. First create it with 0 pitch and then try to create it with another value.

**Comment by SociallyIneptWeeb** [comment]
Ok it should be fixed with the new changes, could you pull them and test it out?

**Comment by SociallyIneptWeeb** [comment]
Ok thanks! You can create a pull request for the rmvpe integration if you're able to do so. I'll close this issue for now.
