### ISSUE TITLE
Error in installing fairseq

### ISSUE THREAD

**Issue by swar-s** [SociallyIneptWeeb/AICoverGen#120]
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\users\kiit\appdata\local\programs\python\python38\include -Ic:\users\kiit\appdata\local\programs\python\python38\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" /EHsc /Tpfairseq/clib/libbleu/libbleu.cpp 
/Fobuild\temp.win-amd64-cpython-38\Release\fairseq/clib/libbleu/libbleu.obj -std=c++11 -O3
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      libbleu.cpp
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\yvals.h(20): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2  
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

**Comment by TheRealMiRRoRMaN** [comment]
same problem here. got 2 3090's and win 10, anaconda, made the environment 3.9, tried for days and days and nothing. 
tried everything. also installing via conda like they say but that never ends, it wont solve the environment etc etc etc.
also tried the editable ./ install thing, nothing. it just isnt able to install fairseq. must be a linux thing or something.

**Comment by Erenkrmt** [comment]
You need to download vs builld tools -> start -> visual studio build tools 2022 -> modify -> downloadd Desktop Development with C++, that should fix it.

**Comment by okejadi** [comment]
what @Erenkrmt is true, thanks for the instruction
