### ISSUE TITLE
Is there any way to do this using AMD GPU?

### ISSUE THREAD

**Issue by anywindo** [SociallyIneptWeeb/AICoverGen#126]
I'm getting error when trying to do it in my local system.

"RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU.."

Sorry, i'm new to PyTorch

**Comment by Blane187** [comment]
you have NIVIDIA GPU?

**Comment by Blane187** [comment]
you using linux or windows?

**Comment by Blane187** [comment]
try use this code  for windows. 
pip install torch-directml

[if it doesn't work, I also don't know :)]

**Comment by anywindo** [comment]
Some sources say i need to use Linux due to poor support for AMD GPUs

**Comment by Blane187** [comment]
If that's the problem, I also don't know.
