### ISSUE TITLE
python src/webui.py complains about this

### ISSUE THREAD

**Issue by arch2kx** [SociallyIneptWeeb/AICoverGen#147]
Here's what's happening...

INFO:faiss.loader:Loading faiss with AVX2 support.
INFO:faiss.loader:Successfully loaded faiss with AVX2 support.
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/home/a2nc7n/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:httpx:load_verify_locations cafile='/home/a2nc7n/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpcore.connection:connect_tcp.started host='api.gradio.app' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.started host='checkip.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:matplotlib:matplotlib data path: /home/a2nc7n/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/a2nc7n/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/a2nc7n/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/a2nc7n/.cache/matplotlib/fontlist-v390.json
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7cf8ad29c3d0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7cf8ad238950> server_hostname='api.gradio.app' timeout=3
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7cf8acddfa10>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7cf8ad238b00> server_hostname='checkip.amazonaws.com' timeout=3
Traceback (most recent call last):
  File "/home/a2nc7n/codes/AICoverGen/AICoverGen/src/webui.py", line 317, in <module>
    app.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'enable_queue'
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7cf8ad2ea4d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7cf8ad2dd9d0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'', [(b'Date', b'Fri, 20 Sep 2024 11:26:34 GMT'), (b'Content-Type', b'text/plain;charset=UTF-8'), (b'Content-Length', b'13'), (b'Connection', b'keep-alive'), (b'Server', b'nginx'), (b'Vary', b'Origin'), (b'Vary', b'Access-Control-Request-Method'), (b'Vary', b'Access-Control-Request-Headers')])
INFO:httpx:HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Fri, 20 Sep 2024 11:26:34 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'21'), (b'Connection', b'keep-alive'), (b'Server', b'nginx/1.18.0'), (b'Access-Control-Allow-Origin', b'*')])
INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /api/telemetry/gradio/initiated HTTP/11" 200 0

**Comment by JackismyShephard** [comment]
@arch2kx I think this is due to this app running on an older version of gradio. You can check out my fork of this app here https://github.com/JackismyShephard/ultimate-rvc if you are in a working up to date version 😄

**Comment by arch2kx** [comment]
i have an arch distro, so im not sure that installing it would actually work...

**Comment by arch2kx** [comment]
@JackismyShephard ok, offtopic here but how do i fix this for your program:
CUDA out of memory. Tried to allocate 186.00 MiB. GPU 0 has a total capacty of 3.81 GiB of which 177.56 MiB is free. Including non-PyTorch memory, this process has 3.22 GiB memory in use. Of the allocated memory 2.02 GiB is allocated by PyTorch, and 1.11 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by arch2kx** [comment]
nevermind, works now
