### ISSUE TITLE
[Feature request] I want this program to also be able to save acapella of AI-cover version of song

### ISSUE THREAD

**Issue by Aosneg** [SociallyIneptWeeb/AICoverGen#18]
I want this program to also be able to save the acapella of the AI-cover version of the song. Is it possible to do this? It would be useful because there are some cases where the instrumental part cannot be cleaned well enough by using AI, but the AI-generated vocal part looks good enough to use with the official instrumental version or with a manually cleaned instrumental track.

**Comment by SociallyIneptWeeb** [comment]
Ok I'll add that in, thanks for suggesting!

**Comment by Aosneg** [comment]
Thanks! Your program is amazing!
