### ISSUE TITLE
[Feature request] Add support for AMD-GPUs?

### ISSUE THREAD

**Issue by TiltingTrain** [SociallyIneptWeeb/AICoverGen#19]
It would be nice to be able to run that locally on an AMD GPU (maybe by using DirectML?)

**Comment by SociallyIneptWeeb** [comment]
Have you tried it with an AMD GPU? Were there any errors?

**Comment by TiltingTrain** [comment]
Yes, this is the Error I get: 
```gradio.exceptions.Error: 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx'```

See the whole message bellow
![Error message](https://github.com/SociallyIneptWeeb/AICoverGen/assets/129487367/a4392bc7-856e-4174-9bad-ad893f83adad)

**Comment by SociallyIneptWeeb** [comment]
Unfortunately, _"AMD Radeon GPUs are not supported at this time"_ according to the Ultimate Vocal Remover GUI official Github Page. https://github.com/Anjok07/ultimatevocalremovergui#other-application-notes

**Comment by Denis6902** [comment]
> 

I found UVR for AMD https://github.com/Aloereed/ultimatevocalremovergui-directml

**Comment by SociallyIneptWeeb** [comment]
Did you find one for rvc voice conversion as well?

**Comment by Denis6902** [comment]
> Did you find one for rvc voice conversion as well?

Yes, https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC0813AMD_Intel.7z

**Comment by SociallyIneptWeeb** [comment]
It seems that in order to accomodate for AMD gpus, a lot of refactoring and extra code will have to be added, both for vocal separation and rvc voice conversion which I do not have the time for, so for now you will have to use the colab version.

**Comment by sukualam** [comment]
just install latest hackintosh (ventura and up) and you can utilizing coreml or mps with amd gpus , mine is rx560 and is working better than directml on windows
