### ISSUE TITLE
[Feature Request] save only vocal

### ISSUE THREAD

**Issue by Hulababa-22** [SociallyIneptWeeb/AICoverGen#22]
can you make a checkbox or a button that saves only the vocal of the converted voice
or alternatively make it so that the music volume can be turned off completely
(if there's a question about this request sry for not answering... timezone diffrence and school)

**Comment by SociallyIneptWeeb** [comment]
The checkbox for keep intermediate files saves the vocals of the converted voice and any other files that you may need in the song_output/id folder. You can delete the rest of the files that you don't need.

**Comment by Hulababa-22** [comment]
Oh ok thx i thought it was only the songs vocal not the converted one
