### ISSUE TITLE
Running on CPU instead of GPU

### ISSUE THREAD

**Issue by syedusama5556** [SociallyIneptWeeb/AICoverGen#23]
i have 3060 6GB gpu on a laptop , when I run webui it works CPU based and only the model is loaded in the GPU but all the processing is  done but CPU & RAM. is this not optimized for GPU

**Comment by SociallyIneptWeeb** [comment]
If you only have 6gb of vram, it will automatically switch over to cpu so as to avoid out of memory errors. Even on 12GB of vram, it also uses some cpu for processing.
