### ISSUE TITLE
[Feature Request] Allow sharing of webui over local network

### ISSUE THREAD

**Issue by harborwater** [SociallyIneptWeeb/AICoverGen#25]
Instead of using a gradio tunnel to reach the webui when it resides on another machine when running locally, why not add something similar to how [textgen-webui](https://github.com/oobabooga/text-generation-webui) does it. For example, adding a flag to the webui.py like `--listen` which would allow the web server to listen on a port that is available a local network. This could be useful for if people are running a dedicated machine or VM on their home network.

**Comment by SociallyIneptWeeb** [comment]
I have added that functionality, so feel free to test it out!

**Comment by harborwater** [comment]
Just tested it seems to be working great! 👍
