### ISSUE TITLE
Issue with models only running on CPU, no GPU utilization

### ISSUE THREAD

**Issue by harborwater** [SociallyIneptWeeb/AICoverGen#26]
I have been playing round with the latest update and I have noticed that I am having an issue with the models only using the CPU no GPU utilization, I am positive that I have all the required dependencies installed. to me this looks like that there is an issue with accessing CUDA? I have the CUDA toolkit installed. I am running a system with `Ubuntu 22.04.3 LTS | 2x RTX 3060 12GB Driver Version: 535.54.03`

 `[W:onnxruntime:Default, onnxruntime_pybind_state.cc:640 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.`

**Comment by SociallyIneptWeeb** [comment]
Can you ensure that you have onnxruntime_gpu pip installed?

**Comment by harborwater** [comment]
Here is my output from the terminal:
 `pip install onnxruntime-gpu:
Requirement already satisfied: onnxruntime-gpu in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (1.15.1)
Requirement already satisfied: coloredlogs in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from onnxruntime-gpu) (23.5.26)
Requirement already satisfied: numpy>=1.21.6 in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from onnxruntime-gpu) (1.23.5)
Requirement already satisfied: packaging in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from onnxruntime-gpu) (23.1)
Requirement already satisfied: protobuf in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from onnxruntime-gpu) (4.24.0)
Requirement already satisfied: sympy in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from onnxruntime-gpu) (1.12)
Requirement already satisfied: humanfriendly>=9.1 in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath>=0.19 in /home/gob/miniconda3/envs/acg/lib/python3.9/site-packages (from sympy->onnxruntime-gpu) (1.3.0)
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063`

**Comment by SociallyIneptWeeb** [comment]
What model is your GPU?

**Comment by harborwater** [comment]
RXT 3060 12gb variant

**Comment by SociallyIneptWeeb** [comment]
Strange, I also have the same model but I don't seem to be facing this issue.

**Comment by harborwater** [comment]
Do you have cuDNN installed by any chance?

**Comment by SociallyIneptWeeb** [comment]
Yes I do have it installed. Maybe you could try installing it?

**Comment by harborwater** [comment]
For some reason it didn't work on the first install, so I reinstalled it using `apt-get install nvidia-cudnn` and it now zooming along just fine

**Comment by harborwater** [comment]
Update, it broke

**Comment by harborwater** [comment]
Here is the error; 

Traceback (most recent call last):
  File "/home/gob/AICoverGen/src/main.py", line 254, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, index_rate, is_webui)
  File "/home/gob/AICoverGen/src/main.py", line 167, in voice_change
    rvc_infer(rvc_index_path, index_rate, vocals_path, output_path, pitch_change, cpt, version, net_g, tgt_sr, vc, hubert_model)
  File "/home/gob/AICoverGen/src/rvc.py", line 147, in rvc_infer
    audio_opt = vc.pipeline(hubert_model, net_g, 0, audio, input_path, times, pitch_change, 'rmvpe', index_path, index_rate, if_f0, 3, tgt_sr, 0, 0.25, version, 0.33, None)
  File "/home/gob/AICoverGen/src/vc_infer_pipeline.py", line 549, in pipeline
    pitch, pitchf = self.get_f0(
  File "/home/gob/AICoverGen/src/vc_infer_pipeline.py", line 326, in get_f0
    self.model_rmvpe = RMVPE(
  File "/home/gob/AICoverGen/src/rmvpe.py", line 346, in __init__
    self.model = self.model.to(device)
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 202, in _apply
    self._init_flat_weights()
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 139, in _init_flat_weights
    self.flatten_parameters()
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 169, in flatten_parameters
    not torch.backends.cudnn.is_acceptable(fw.data)):
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/backends/cudnn/__init__.py", line 97, in is_acceptable
    if not _init():
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/torch/backends/cudnn/__init__.py", line 60, in _init
    raise RuntimeError(base_error_msg)
RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0) but found runtime version (8, 2, 4). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/gob/miniconda3/envs/acg/lib/python3.9/site-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/home/gob/AICoverGen/src/main.py", line 272, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "/home/gob/AICoverGen/src/main.py", line 76, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: 'cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0) but found runtime version (8, 2, 4). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.'

**Comment by SociallyIneptWeeb** [comment]
You can try doing
conda install cudnn=8.7.0

**Comment by harborwater** [comment]
Here is the result of that command;

`gob@box-01:~/AICoverGen$ conda install cudnn=8.7.0`
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudnn=8.7.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by SociallyIneptWeeb** [comment]
You might have to add a `-c conda-forge`

**Comment by harborwater** [comment]
Output of  `gob@box-01:~$ conda install -c conda-forge cudnn=8.7.0`

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudnn=8.7.0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by SociallyIneptWeeb** [comment]
Try uninstalling cudnn and installing it again maybe?

**Comment by SociallyIneptWeeb** [comment]
https://developer.nvidia.com/rdp/cudnn-archive
You can try installing cuDNN v8.7.0 (November 28th, 2022), for CUDA 11.x

**Comment by harborwater** [comment]
Could it be that maybe I have the wrong version of CUDA installed? I just checked my version which is  12.2

**Comment by SociallyIneptWeeb** [comment]
Yah that may be the case, in the requirements.txt, it uses torch==2.0.1+cu118, so cuda 11.8

**Comment by harborwater** [comment]
I see, I'll figure out how to downgrade and I'll let you know if it is successful 👍

**Comment by harborwater** [comment]
So I have downgraded the CUDA version to 11.8 and installed cuDNN and I am still having no luck. All the dependencies have been installed which doesn't make sense why it wouldn't work. From POV it seems that in the pipeline it wants to use CPU for UVR and the other models, the only time it runs on GPU seems to be when it is done running the separation of vocals from music.

**Comment by SociallyIneptWeeb** [comment]
I have hardcoded the code to use the GPU at index 0 in this line `device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')`. Maybe it's because you have the GPU at a different index?

**Comment by DragonTornado** [comment]
I had the exact same issue on Debian 12 with a 1070 using pyenv [3.10.12].
It seemed when I edited the src/mdx.py so that "import torch" was before "import onnxruntime as ort" and "import numpy as np" the gpu seemed to work.
My guess is that the onnxruntime is using the libraries from torch on linux and makes it so import order matters on linux.
Either that or I installed python3-pycuda, but I highly doubt that since that would target against the default python [3.11] install.

**Comment by SociallyIneptWeeb** [comment]
Oh yah I also only tested this against python 3.9, I'm not sure if other versions may be causing this issue.

**Comment by DragonTornado** [comment]
It definitely works on 3.10

**Comment by harborwater** [comment]
I think I might have found this issue, can you confirm for me that you have cuDNN 8.7.0 installed?

**Comment by harborwater** [comment]
When I go to install cuDNN I get the error `cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0) but found runtime version (8, 4, 1).` However this fixes the `onnxruntime_pybind_state.cc:640 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider.` This leads me to believe that in order to solve the problem I need to find the cuDNN 8.7.0 conda package which I can't seem to find it in the conda packages

**Comment by SociallyIneptWeeb** [comment]
> https://developer.nvidia.com/rdp/cudnn-archive You can try installing cuDNN v8.7.0 (November 28th, 2022), for CUDA 11.x

Yes, maybe you could try installing it using this?

**Comment by harborwater** [comment]
so I just tried running `conda install -c conda-forge cudnn -n env` out of curiosity and it's now working. going to close this issue and do some more testing. I will reopen issue if issue returns
