### ISSUE TITLE
Download from a YouTube Playlist URL took forever

### ISSUE THREAD

**Issue by okejadi** [SociallyIneptWeeb/AICoverGen#27]
It seems that the download process took forever if I gave a YT URL song which I played from a playlist.

example URL: 
https://www.youtube.com/watch?v=LrwC2Xu2POs&list=PLcEGijvykxZGPfuRkWle36VHV8Px9kvYT&index=29&ab_channel=spitzclips 

I need to restart the runtime and gave only the short video link for it to work:
https://www.youtube.com/watch?v=LrwC2Xu2POs

not an important job though but definitely a bit annoying when accidentally provided the wrong format and need to reset the runtime 😅

**Comment by okejadi** [comment]
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/35001086/3eaea3c1-b5de-46a0-b2db-4866ce164fc6)

I think it just want to downloads every video on the playlist lol

**Comment by SociallyIneptWeeb** [comment]
I have fixed it to only download a single video from the playlist. You can pull the new changes and test it out!

**Comment by okejadi** [comment]
It's fixed now, thank you!!
