### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by SubmitCodes** [SociallyIneptWeeb/AICoverGen#29]
Hello
So I have been trying to use this on my 4070ti with 12gb for context
I have not been successful with that
kept getting many errors
Here is the first one that I get when I put a yt link(not Playlist)

![Screenshot 2023-08-13 203445](https://github.com/SociallyIneptWeeb/AICoverGen/assets/112579527/bd9f64ec-586f-4cac-9f97-134ce46a8d16)
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/112579527/596707e0-0b35-4b99-9b8d-daba3ded81c9)

And this one when I upload a song, tried to put it in the installation folder didn't work
![Screenshot 2023-08-13 204232](https://github.com/SociallyIneptWeeb/AICoverGen/assets/112579527/9f1ad22c-53df-420a-9b61-eacfac015e85)
![Screenshot 2023-08-13 at 21-03-16 Memo Notepad](https://github.com/SociallyIneptWeeb/AICoverGen/assets/112579527/7134609a-d2b7-4bd2-bb9a-cea56717709e)

what do I do

**Comment by SociallyIneptWeeb** [comment]
Could you send the youtube link here so I can test it?

**Comment by SubmitCodes** [comment]
> Could you send the youtube link here so I can test it?

It's all yt links not just one, sorry if I wasn't clear enough.

**Comment by SubmitCodes** [comment]
> For youtube links, it should be working, maybe it's because of a weird youtube title? As for local upload of audio file, you only need to click upload, select the file from the file browser, set your desired settings and then click generate. There's no need to put any file in any installation folder. At least in the latest version, so maybe you could try pulling the latest changes and then testing the local file upload?

I am on the latest changes and getting those errors unfortunately, I have tried multiple files/yt links, and it didn't work, I also tried other browsers and still.

**Comment by SociallyIneptWeeb** [comment]
Haha, I'm not sure what the issue is, but for now I guess you have to use the colab version...

**Comment by SubmitCodes** [comment]
> Haha, I'm not sure what the issue is, but for now I guess you have to use the colab version...

No problem haha, I always have errors when I want to have fun with something, just a normal day :)

**Comment by SubmitCodes** [comment]
> Haha, I'm not sure what the issue is, but for now I guess you have to use the colab version...

I seriously don't know why this got fixed, but I did a fresh installation of windows and now it works!
(I didn't do it because of this lol)

**Comment by SociallyIneptWeeb** [comment]
Lol ok great 👍
