### ISSUE TITLE
[Questions] Can we make an options for vocals only?

### ISSUE THREAD

**Issue by Krookjk** [SociallyIneptWeeb/AICoverGen#39]
Sometimes the AI just skip a part and set it to the backup vocals and it makes the songs feels uncompleted. Like "Idol" from YOASOBI for example, it puts the vocals on 0:11 to the backup vocals and it makes the AI didn't process it. So can you make an option that I can upload the vocals like Mangio RVC Fork and process all of it?

**Comment by SociallyIneptWeeb** [comment]
Do you mean just run voice conversion on an audio file which only contains the vocals?

**Comment by Krookjk** [comment]
> Do you mean just run voice conversion on an audio file which only contains the vocals?

Yeah, that's right

**Comment by SociallyIneptWeeb** [comment]
I think if thats the case you can simply use the mangio rvc fork since they do just that. This repo is mainly for people to run the entire cover generation pipeline, from vocal separation, voice conversion to audio mixing. The mangio rvc fork is more for simply voice conversion which is what you want.

**Comment by Krookjk** [comment]
> I think if thats the case you can simply use the mangio rvc fork since they do just that. This repo is mainly for people to run the entire cover generation pipeline, from vocal separation, voice conversion to audio mixing. The mangio rvc fork is more for simply voice conversion which is what you want.

But the Mangio RVC Fork result feels a little bit bad. Sometimes they cannot process high tones vocals

**Comment by SociallyIneptWeeb** [comment]
Not sure, haha, the only things I add on to the voice conversion, is the vocal separation and audio mixing

**Comment by Krookjk** [comment]
> Not sure, haha, the only things I add on to the voice conversion, is the vocal separation and audio mixing

Well, thank you for your explanation
