### ISSUE TITLE
Regex  issue

### ISSUE THREAD

**Issue by AkiraRy** [SociallyIneptWeeb/AICoverGen#4]
If you paste the share link of yt video it won`t work
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/106382882/a402ade9-c915-4bc9-9d82-d660399199ff)
If you paste link with channel argument as in "https://www.youtube.com/watch?v=C7aCInI-g10&ab_channel=HARU"
it also will give problem
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/106382882/192a46bb-75a8-49e1-8c40-b492853c5d18)

**Comment by AkiraRy** [comment]
the solution is to pass link in double quotes for windows and single for unix like system. 

Although it doesn`t seem to work if i send the link to yt video that is in playlist. Seems like it starts to download every songs in that playlist  

https://github.com/SociallyIneptWeeb/AICoverGen/assets/106382882/b578a425-cfd4-4d4f-8219-6a5751cae73d

**Comment by SociallyIneptWeeb** [comment]
Should be fixed with the new pull request, try pulling the new changes in the repo and try again.
