### ISSUE TITLE
SoX could not be found!

### ISSUE THREAD

**Issue by MarshalSan** [SociallyIneptWeeb/AICoverGen#40]
Ran the update today, 

I got the error:

'sox' is not recognized as an internal or external command,
operable program or batch file.
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

But during the update process, this line was there:
Installing collected packages: sox
Successfully installed sox-1.4.1

I'm considering installing Sox directly from the link that the prompt gives, but the version is 14.4.2, will that cause any issues?

**Comment by SociallyIneptWeeb** [comment]
You only need to pip install the requirements again after updating

**Comment by MarshalSan** [comment]
I ran the installation again just to be sure but the error is coming up again. 

During usage though I don't seem to be encountering any noticeable issues.

This is what shows up when I run the webui:

> W:\AI\Git\AICoverGen>python src/webui.py
> 'sox' is not recognized as an internal or external command,
> operable program or batch file.
> SoX could not be found!
> 
>     If you do not have SoX, proceed here:
>      - - - http://sox.sourceforge.net/ - - -
> 
>     If you do (or think that you should) have SoX, double-check your
>     path variables.
> 
> 2023-08-28 19:43:39 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
> 2023-08-28 19:43:39 | INFO | faiss.loader | Loading faiss with AVX2 support.
> 2023-08-28 19:43:39 | INFO | faiss.loader | Could not load library with AVX2 support due to:
> ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
> 2023-08-28 19:43:39 | INFO | faiss.loader | Loading faiss.
> 2023-08-28 19:43:39 | INFO | faiss.loader | Successfully loaded faiss.
> Running on local URL:  http://127.0.0.1:7860


I'm also running an outdated version of pip (if that can be causing issues, i figured the version currently installed came with AICoverGen) 

> WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
> You should consider upgrading via the 'C:\Users\MSi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

**Comment by SociallyIneptWeeb** [comment]
Oh I see I didn't realize I already have sox installed. I'll update the readme to include the instructions to install sox. For now you can follow this guide to install sox. https://www.tutorialexample.com/a-step-guide-to-install-sox-sound-exchange-on-windows-10-python-tutorial/
