### ISSUE TITLE
some lyrics skipped

### ISSUE THREAD

**Issue by dei0ces** [SociallyIneptWeeb/AICoverGen#41]
for some songs some lyrics are skipped by ai, I think ai thinks the vocal part of instrumental.
how can I fix it?

**Comment by SociallyIneptWeeb** [comment]
This is a limitation with the vocal separation model, sometimes it doesn't properly detect the vocals.

**Comment by dei0ces** [comment]
some vocal separators online does a better job, can we find and put a better way to detect the vocals?

**Comment by SociallyIneptWeeb** [comment]
Most better ones require specific software and requirements that will drastically increase setup complexity and reduce the scope of users who can use this. Unless I find one that doesn't have these trade-offs, the current vocal separation models will have to do. You can try using ultimate vocal remover gui and play around with the different types of models.

**Comment by dei0ces** [comment]
thanks

**Comment by ElmorenohWTF** [comment]
Perhaps you could add an option for people who prefer to have a more complicated or time-consuming setup but with better vocals separation? And if you can use the regular one, you just don't use that option (and you don't have to wait for its setup)
