### ISSUE TITLE
[Questions] Can we return the pitch changing from -20 to 20?

### ISSUE THREAD

**Issue by ThanhMinh200** [SociallyIneptWeeb/AICoverGen#42]
Sometimes I want my vocals is deeper just a little bit, but after this new update, the gap of the number changes so much that when I just change the pitch to -1, the female vocals became male vocals and sometimes the pitch just change uncontrollable and it makes the vocals deeper or softer than the original dataset voices. Can you bring that back again?

**Comment by SociallyIneptWeeb** [comment]
To change the pitch by just a little bit, you should use the second pitch change for overall. It does slight adjustments while keeping the vocals on key with the instrumentals

**Comment by ThanhMinh200** [comment]
> To change the pitch by just a little bit, you should use the second pitch change for overall. It does slight adjustments while keeping the vocals on key with the instrumentals

But I dont want to also change the pitch of the music too

**Comment by SociallyIneptWeeb** [comment]
That would result in the vocals being off key

**Comment by ThanhMinh200** [comment]
> That would result in the vocals being off key

Uh, I dont really get it. I didn't have any problems before the update

**Comment by SociallyIneptWeeb** [comment]
If the pitch of the vocals are changed within 12 semitones without the instrumentals, this would result in the singer singing in a different key from the music. Off key sounds like when you go to the karaoke and that one tone-deaf friend tries to sing unravel.

**Comment by ThanhMinh200** [comment]
> If the pitch of the vocals are changed within 12 semitones without the instrumentals, this would result in the singer singing in a different key from the music. Off key sounds like when you go to the karaoke and that one tone-deaf friend tries to sing unravel.

I see, but can you bring that back as an option?

**Comment by ThanhMinh200** [comment]
> Um in what case would you want the vocals to be off key?

That's ok. Off-key vocals don't matter on me

**Comment by SociallyIneptWeeb** [comment]
Does changing the pitch of the bgm matter to you?

**Comment by ThanhMinh200** [comment]
> Does changing the pitch of the bgm matter to you?

Yeah. I want to have the original bgm

**Comment by SociallyIneptWeeb** [comment]
In that case, you can run `git checkout 46a5ff7db1560a2105b65d562d2e41326174ae44` in a terminal at the AICoverGen directory. This will revert your version of AICoverGen to the one with the pitch change specificity that you want.

**Comment by ThanhMinh200** [comment]
> In that case, you can run `git checkout 46a5ff7db1560a2105b65d562d2e41326174ae44` in a terminal at the AICoverGen directory. This will revert your version of AICoverGen to the one with the pitch change specificity that you want.

Do you have the colab version? I usually use that because my PC is kinda slow tbh

**Comment by ThanhMinh200** [comment]
> In that case, you can run `git checkout 46a5ff7db1560a2105b65d562d2e41326174ae44` in a terminal at the AICoverGen directory. This will revert your version of AICoverGen to the one with the pitch change specificity that you want.

Help please

**Comment by SociallyIneptWeeb** [comment]
U can create a new code cell below clone repository and paste that command. Then just do the usual runtime run all

**Comment by ThanhMinh200** [comment]
> U can create a new code cell below clone repository and paste that command. Then just do the usual runtime run all

Thank you so much
