### ISSUE TITLE
No module named "requests" error while installing

### ISSUE THREAD

**Issue by Sarlex6** [SociallyIneptWeeb/AICoverGen#44]
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/122372608/a8f40b68-6e26-4857-a812-677f2d250cc2)
I got this error while downloading the required models, how can I fix this?

**Comment by SociallyIneptWeeb** [comment]
Follow the readme guide step by step and pip install the requirements first

**Comment by Sarlex6** [comment]
I did, I even checked and I have all of them installed

**Comment by SociallyIneptWeeb** [comment]
Do you have them installed in a venv or a conda env? You may need to specify whether to use the python in the venv rather than use your system's python runtime.

**Comment by Sarlex6** [comment]
Oh yeah that helped, thanks!
