### ISSUE TITLE
Error when installing dependencies

### ISSUE THREAD

**Issue by Aadit420** [SociallyIneptWeeb/AICoverGen#45]
i've received this error message when running pip -r requirements.ext
Error message:  Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

When downloading this, I cannot find the necessary dependency.

What do i do?

**Comment by SociallyIneptWeeb** [comment]
You can go to the link at download Microsoft visual c++ 14.0 or greater

**Comment by Aadit420** [comment]
turns out I needed to install something within visual studio to solve the issue, thanks for helping
