### ISSUE TITLE
Model file not found despite being there

### ISSUE THREAD

**Issue by Aadit420** [SociallyIneptWeeb/AICoverGen#46]
I've loaded the model file to the specific folder in the webUI, but it doesn't detect it
[WinError 267] The directory name is invalid: 'C:\\\\Users\\\\USER\\\\Downloads\\\\Easysongcover\\\\AICoverGen\\\\rvc_models\\\\[model].pth'"

**Comment by SociallyIneptWeeb** [comment]
You have to create a new folder in the rvc_models with a unique name you would like to give the voice model. Then, transfer the .pth file into that folder.

**Comment by SociallyIneptWeeb** [comment]
https://github.com/SociallyIneptWeeb/AICoverGen#manual-download-of-rvc-models
You can refer to this section of the readme for how the directory structure should look like

**Comment by Aadit420** [comment]
yep, solved
Thank you so much!
