### ISSUE TITLE
Reverb control Generate error

### ISSUE THREAD

**Issue by yammie02** [SociallyIneptWeeb/AICoverGen#47]
When reverb control is turned off, it plays the same as the original voice...

**Comment by SociallyIneptWeeb** [comment]
Can you specify the settings you used?

**Comment by yammie02** [comment]
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/64888678/dfd57572-895a-4b97-85de-20f0dde6ae5f)

Plus: I'm a local user

**Comment by SociallyIneptWeeb** [comment]
Maybe try increasing the dryness level of the vocals to 100%?

**Comment by yammie02** [comment]
It works fine! Thank you!

**Comment by yammie02** [comment]
It works fine! Thank you!
