### ISSUE TITLE
Auto-tune detector ?

### ISSUE THREAD

**Issue by neoluigi4123** [SociallyIneptWeeb/AICoverGen#48]
A parameter that can fix / control autotune on a song by "unauto_tune" the voice and / or add autotune to the AI-vocal

**Comment by SociallyIneptWeeb** [comment]
Unauto_tune Not really possible as the pitch is inferred directly from the original vocal audio with RVC. Autotune is kinda rare because people usually want the voice to follow the pitch of the original singer

**Comment by neoluigi4123** [comment]
Alright, well, thanks for the reply, I totally understand why it cannot really be made. Well, another Ai to make lol.
