### ISSUE TITLE
sox

### ISSUE THREAD

**Issue by aifusionstudio** [SociallyIneptWeeb/AICoverGen#49]
Hi there,
I see this warning, is it required?
'sox' is not recognized as an internal or external command,
operable program or batch file.
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

**Comment by NightMortal** [comment]
You need to go into your environment path and add sox there for it to show up in the terminal. Click new and add the path of the file. 
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/129024235/287eb48b-1b89-4482-b10f-c51be975c0d4)

**Comment by SociallyIneptWeeb** [comment]
If you tried running this on colab notebook, I have added a commit to fix this issue, so deleting and restarting the runtime should make it work now.

**Comment by aifusionstudio** [comment]
Appreciate your work in providing this code. Thanks a lot. 
That error went away. 
Is this of any concern faiss avx2?
2023-09-06 07:52:33 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-09-06 07:52:33 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-09-06 07:52:33 | INFO | faiss.loader | Loading faiss.
2023-09-06 07:52:34 | INFO | faiss.loader | Successfully loaded faiss.

**Comment by SociallyIneptWeeb** [comment]
No its not an issue. It'll still work with that warning.
