### ISSUE TITLE
Requirements.txt error

### ISSUE THREAD

**Issue by FruitsAndVegetables** [SociallyIneptWeeb/AICoverGen#51]
![Screenshot_20230906-090922_1](https://github.com/SociallyIneptWeeb/AICoverGen/assets/99060046/3a509e24-494c-4c0f-8a6c-d91eb098faa6)

So im currently using the colab, but it wouldn't let me because of the requirements error?

**Comment by SociallyIneptWeeb** [comment]
Um did you click runtime and run all?

**Comment by FruitsAndVegetables** [comment]
> Um did you click runtime and run all?

Its working fine now thx! i guess the problem is my google account?

**Comment by SociallyIneptWeeb** [comment]
Ok that's good to know.
