### ISSUE TITLE
Fairseq refuses to install off of Requirments

### ISSUE THREAD

**Issue by snintendog** [SociallyIneptWeeb/AICoverGen#58]
python 3.9 have Git, sox, ffmpeg, my paths are set. the error returns stuff about C++ 2014 not existing i have the 2015-2022 installed due to being on win 10. Programing is Not my thing at all. This is after tyring to figure out why i cant get the MXmodels DLed for it.

**Comment by snintendog** [comment]
![Python](https://github.com/SociallyIneptWeeb/AICoverGen/assets/5448989/623aa9eb-0ac0-47b3-9691-5a276a33999d)
the Error in question

**Comment by SociallyIneptWeeb** [comment]
https://github.com/SociallyIneptWeeb/AICoverGen/issues/45

It's the same as this issue, you prob have to install something within visual studio

**Comment by snintendog** [comment]
Installing Visual build Studio tools seemed to get me past it.. Might want to add that as a prerequisite. Completely halted my install.

**Comment by snintendog** [comment]
had a BSOD while making a cover.
![Python 2](https://github.com/SociallyIneptWeeb/AICoverGen/assets/5448989/51669a6b-bf3b-4912-a24b-218e31131d81)
i have no clue what i need now.

**Comment by snintendog** [comment]
Needed to force reinstall Gardio, FFMPEG, FFMPY in the Python instance(READ HARD DELETE THEIR FOLDERS --force-Reinstall wasnt enough.), And on a side note the Magio RVC fork needed its */Lib/infer_pack restored as well for its lib.infer_pack.model error just grab it from the git. Should anyone come across this while Searching after a bad Crash Mid training/ Mid Cover.
