### ISSUE TITLE
Issue while starting locally 

### ISSUE THREAD

**Issue by Sigi3012** [SociallyIneptWeeb/AICoverGen#63]
### I have followed the installation guide and have tried troubleshooting this myself, alas no luck
---
AICoverGen on  main via 🐍 v3.9.4 took 2s
❯ python src\main.py
2023-09-23 19:52:20 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-09-23 19:52:20 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-09-23 19:52:20 | INFO | faiss.loader | Loading faiss.
2023-09-23 19:52:20 | INFO | faiss.loader | Successfully loaded faiss.
usage: main.py [-h] -i SONG_INPUT -dir RVC_DIRNAME -p PITCH_CHANGE [-k | --keep-files | --no-keep-files]
               [-ir INDEX_RATE] [-fr FILTER_RADIUS] [-rms RMS_MIX_RATE] [-palgo PITCH_DETECTION_ALGO]
               [-hop CREPE_HOP_LENGTH] [-pro PROTECT] [-mv MAIN_VOL] [-bv BACKUP_VOL] [-iv INST_VOL]
               [-pall PITCH_CHANGE_ALL] [-rsize REVERB_SIZE] [-rwet REVERB_WETNESS] [-rdry REVERB_DRYNESS]
               [-rdamp REVERB_DAMPING] [-oformat OUTPUT_FORMAT]
main.py: error: the following arguments are required: -i/--song-input, -dir/--rvc-dirname, -p/--pitch-change

AICoverGen on  main via 🐍 v3.9.4 took 6s

This was working for me awhile ago on an older version, I tried to use it again today and had some issues, so I tried updating and still got the same issue.

**Comment by SociallyIneptWeeb** [comment]
It looks like it's setup properly. You can run `python webui.py` instead. Main.py is for people who want to use the cli method, so they have to provide other options

**Comment by Sigi3012** [comment]
Oh that's totally my mistake, thanks and sorry for the inconvenience
