### ISSUE TITLE
Error: 'module 'numpy' has no attribute 'int' when using NumPy 1.20

### ISSUE THREAD

**Issue by Sophaithevoice12** [SociallyIneptWeeb/AICoverGen#64]
Whn I try to covert it say :
-----------------------------
"module 'numpy' has no attribute 'int'.\nnp.int was a deprecated alias for the builtin int. To avoid this error in existing code, use int by itself. Doing this will not modify any behavior and is safe. When replacing np.int, you may wish to use e.g. np.int64 or np.int32 to specify the precision. If you wish to review your current use, check the release note link for additional information.\nThe aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
---------------------------
and when  I try to downgrade it then say :
----------------------------------------------
    raise ImportError("Numba needs NumPy 1.25 or less")
ImportError: Numba needs NumPy 1.25 or less
------------------------------------------------------

**Comment by SociallyIneptWeeb** [comment]
Try to use python 3.9 and reinstall the dependencies
