### ISSUE TITLE
collab with Web UI issue

### ISSUE THREAD

**Issue by gargoylefad** [SociallyIneptWeeb/AICoverGen#78]
when i hit the generate button on Web UI it says:

"Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

i'm using google collab btw.
![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/140941810/9bef8fe1-ddb3-4079-ae1d-5ef927987674)

**Comment by SociallyIneptWeeb** [comment]
Click on runtime in the google colab notebook top navigation bar and change runtime type. Check if you have selected the T4 GPU.

**Comment by SebsBeatz** [comment]
I get the same thing and when i click on T4 GPU it still appears
